package com.PartyPotionTracker;

import lombok.RequiredArgsConstructor;
import net.runelite.api.ItemID;

import java.util.Arrays;
import java.util.Set;
import java.util.stream.Collectors;

@RequiredArgsConstructor
public enum ToaPotions {
    PRAYER_POTION_4(ItemID.PRAYER_POTION4),
    PRAYER_POTION_3(ItemID.PRAYER_POTION3),
    PRAYER_POTION_2(ItemID.PRAYER_POTION2),
    PRAYER_POTION_1(ItemID.PRAYER_POTION1),
    SUPER_RESTORE_4(ItemID.SUPER_RESTORE4),
    SUPER_RESTORE_3(ItemID.SUPER_RESTORE3),
    SUPER_RESTORE_2(ItemID.SUPER_RESTORE2),
    SUPER_RESTORE_1(ItemID.SUPER_RESTORE1),
    SARADOMIN_BREW_4(ItemID.SARADOMIN_BREW4),
    SARADOMIN_BREW_3(ItemID.SARADOMIN_BREW3),
    SARADOMIN_BREW_2(ItemID.SARADOMIN_BREW2),
    SARADOMIN_BREW_1(ItemID.SARADOMIN_BREW1),
    SANFEW_SERUM_4(ItemID.SANFEW_SERUM4),
    SANFEW_SERUM_3(ItemID.SANFEW_SERUM3),
    SANFEW_SERUM_2(ItemID.SANFEW_SERUM2),
    SANFEW_SERUM_1(ItemID.SANFEW_SERUM1),
    DIVINE_SUPER_COMBAT_POTION_4(ItemID.DIVINE_SUPER_COMBAT_POTION4),
    DIVINE_SUPER_COMBAT_POTION_3(ItemID.DIVINE_SUPER_COMBAT_POTION3),
    DIVINE_SUPER_COMBAT_POTION_2(ItemID.DIVINE_SUPER_COMBAT_POTION2),
    DIVINE_SUPER_COMBAT_POTION_1(ItemID.DIVINE_SUPER_COMBAT_POTION1),
    DIVINE_RANGING_POTION_4(ItemID.DIVINE_RANGING_POTION4),
    DIVINE_RANGING_POTION_3(ItemID.DIVINE_RANGING_POTION3),
    DIVINE_RANGING_POTION_2(ItemID.DIVINE_RANGING_POTION2),
    DIVINE_RANGING_POTION_1(ItemID.DIVINE_RANGING_POTION1),
    NECTAR_1(ItemID.NECTAR_1),
    NECTAR_2(ItemID.NECTAR_2),
    NECTAR_3(ItemID.NECTAR_3),
    NECTAR_4(ItemID.NECTAR_4),
    BLESSED_CRYSTAL_SCARAB_1(ItemID.BLESSED_CRYSTAL_SCARAB_1),
    BLESSED_CRYSTAL_SCARAB_2(ItemID.BLESSED_CRYSTAL_SCARAB_2),
    TEARS_OF_ELIDINIS_1(ItemID.TEARS_OF_ELIDINIS_1),
    TEARS_OF_ELIDINIS_2(ItemID.TEARS_OF_ELIDINIS_2),
    TEARS_OF_ELIDINIS_3(ItemID.TEARS_OF_ELIDINIS_3),
    TEARS_OF_ELIDINIS_4(ItemID.TEARS_OF_ELIDINIS_4),
    AMBROSIA_1(ItemID.AMBROSIA_1),
    AMBROSIA_2(ItemID.AMBROSIA_2),
    SILK_DRESSING_1(ItemID.SILK_DRESSING_1),
    SILK_DRESSING_2(ItemID.SILK_DRESSING_2);


    public final int itemID;
    private static final Set<Integer> ITEM_IDS = Arrays.stream(values())
            .map(p -> p.itemID)
            .collect(Collectors.toSet());

    public static Boolean isPotion(int itemID){
        return ITEM_IDS.contains(itemID);
    }
}
